// This is auto-generated by scripts/downloadReleases.js

export const supportedReleases = [
  "3.7.3",
  "3.6.3",
  "3.5.1",
  "3.3.3",
  "3.1.6",
  "3.0.1",
  "2.8.1",
  "2.7.2",
  "2.4.1"
] as const;

export type ReleaseVersions =
  | "3.7.3"
  | "3.6.3"
  | "3.5.1"
  | "3.3.3"
  | "3.1.6"
  | "3.0.1"
  | "2.8.1"
  | "2.7.2"
  | "2.4.1";
