export type AllDocsPages =
  | "Nightly Builds.md"
  | "declaration-files/By Example.md"
  | "declaration-files/Consumption.md"
  | "declaration-files/Deep Dive.md"
  | "declaration-files/Do's and Don'ts.md"
  | "declaration-files/Introduction.md"
  | "declaration-files/Library Structures.md"
  | "declaration-files/Publishing.md"
  | "declaration-files/Templates.md"
  | "declaration-files/templates/global-modifying-module.d.ts.md"
  | "declaration-files/templates/global-plugin.d.ts.md"
  | "declaration-files/templates/global.d.ts.md"
  | "declaration-files/templates/module-class.d.ts.md"
  | "declaration-files/templates/module-function.d.ts.md"
  | "declaration-files/templates/module-plugin.d.ts.md"
  | "declaration-files/templates/module.d.ts.md"
  | "get-started/TS for Functional Programmers.md"
  | "get-started/TS for JS Programmers.md"
  | "get-started/TS for OOPers.md"
  | "get-started/TS for the New Programmer.md"
  | "handbook-v1/Basic Types.md"
  | "handbook-v1/Classes.md"
  | "handbook-v1/Functions.md"
  | "handbook-v1/Generics.md"
  | "handbook-v1/Interfaces.md"
  | "handbook-v1/Literal Types.md"
  | "handbook-v1/Unions and Intersections.md"
  | "handbook-v2/Basics.md"
  | "handbook-v2/Classes.md"
  | "handbook-v2/Everyday Types.md"
  | "handbook-v2/Modules.md"
  | "handbook-v2/More on Functions.md"
  | "handbook-v2/Narrowing.md"
  | "handbook-v2/Object Types.md"
  | "handbook-v2/The Handbook.md"
  | "handbook-v2/Type Declarations.md"
  | "handbook-v2/Understanding Errors.md"
  | "handbook-v2/Type Manipulation/Conditional Types.md"
  | "handbook-v2/Type Manipulation/Generics.md"
  | "handbook-v2/Type Manipulation/Indexed Access Types.md"
  | "handbook-v2/Type Manipulation/Keyof Type Operator.md"
  | "handbook-v2/Type Manipulation/Mapped Types.md"
  | "handbook-v2/Type Manipulation/Template Literal Types.md"
  | "handbook-v2/Type Manipulation/Typeof Type Operator.md"
  | "handbook-v2/Type Manipulation/_Creating Types from Types.md"
  | "javascript/Creating DTS files From JS.md"
  | "javascript/Intro to JS with TS.md"
  | "javascript/JSDoc Reference.md"
  | "javascript/Type Checking JavaScript Files.md"
  | "project-config/Compiler Options in MSBuild.md"
  | "project-config/Compiler Options.md"
  | "project-config/Configuring Watch.md"
  | "project-config/Integrating with Build Tools.md"
  | "project-config/Project References.md"
  | "project-config/tsconfig.json.md"
  | "reference/Advanced Types.md"
  | "reference/Declaration Merging.md"
  | "reference/Decorators.md"
  | "reference/Enums.md"
  | "reference/Experimental ESM Support for Node.md"
  | "reference/Iterators and Generators.md"
  | "reference/JSX.md"
  | "reference/Mixins.md"
  | "reference/Module Resolution.md"
  | "reference/Modules.md"
  | "reference/Namespaces and Modules.md"
  | "reference/Namespaces.md"
  | "reference/Symbols.md"
  | "reference/Triple-Slash Directives.md"
  | "reference/Type Compatibility.md"
  | "reference/Type Inference.md"
  | "reference/Utility Types.md"
  | "reference/Variable Declarations.md"
  | "release-notes/Overview.md"
  | "release-notes/TypeScript 1.1.md"
  | "release-notes/TypeScript 1.3.md"
  | "release-notes/TypeScript 1.4.md"
  | "release-notes/TypeScript 1.5.md"
  | "release-notes/TypeScript 1.6.md"
  | "release-notes/TypeScript 1.7.md"
  | "release-notes/TypeScript 1.8.md"
  | "release-notes/TypeScript 2.0.md"
  | "release-notes/TypeScript 2.1.md"
  | "release-notes/TypeScript 2.2.md"
  | "release-notes/TypeScript 2.3.md"
  | "release-notes/TypeScript 2.4.md"
  | "release-notes/TypeScript 2.5.md"
  | "release-notes/TypeScript 2.6.md"
  | "release-notes/TypeScript 2.7.md"
  | "release-notes/TypeScript 2.8.md"
  | "release-notes/TypeScript 2.9.md"
  | "release-notes/TypeScript 3.0.md"
  | "release-notes/TypeScript 3.1.md"
  | "release-notes/TypeScript 3.2.md"
  | "release-notes/TypeScript 3.3.md"
  | "release-notes/TypeScript 3.4.md"
  | "release-notes/TypeScript 3.5.md"
  | "release-notes/TypeScript 3.6.md"
  | "release-notes/TypeScript 3.7.md"
  | "release-notes/TypeScript 3.8.md"
  | "release-notes/TypeScript 3.9.md"
  | "release-notes/TypeScript 4.0.md"
  | "release-notes/TypeScript 4.1.md"
  | "release-notes/TypeScript 4.2.md"
  | "release-notes/TypeScript 4.3.md"
  | "release-notes/TypeScript 4.4.md"
  | "release-notes/TypeScript 4.5.md"
  | "tutorials/ASP.NET Core.md"
  | "tutorials/Angular.md"
  | "tutorials/Babel with TypeScript.md"
  | "tutorials/DOM Manipulation.md"
  | "tutorials/Gulp.md"
  | "tutorials/Migrating from JavaScript.md"
  | "tutorials/React.md"
  | "tutorials/TypeScript Tooling in 5 minutes.md";
