export type AllDocsPages =
  | "Advanced Types.md"
  | "Basic Types.md"
  | "Classes.md"
  | "Compiler Options in MSBuild.md"
  | "Compiler Options.md"
  | "Configuring Watch.md"
  | "Declaration Merging.md"
  | "Decorators.md"
  | "Enums.md"
  | "Functions.md"
  | "Generics.md"
  | "Integrating with Build Tools.md"
  | "Interfaces.md"
  | "Intro to JS with TS.md"
  | "Iterators and Generators.md"
  | "JSDoc Reference.md"
  | "JSX.md"
  | "Literal Types.md"
  | "Mixins.md"
  | "Module Resolution.md"
  | "Modules.md"
  | "Namespaces and Modules.md"
  | "Namespaces.md"
  | "Nightly Builds.md"
  | "Project References.md"
  | "Symbols.md"
  | "The Handbook.md"
  | "Triple-Slash Directives.md"
  | "Type Checking JavaScript Files.md"
  | "Type Compatibility.md"
  | "Type Inference.md"
  | "Unions and Intersections.md"
  | "Utility Types.md"
  | "Variable Declarations.md"
  | "Get Started/TS for Functional Programmers.md"
  | "Get Started/TS for JS Programmers.md"
  | "Get Started/TS for OOPers.md"
  | "Get Started/TS for the New Programmer.md"
  | "declaration files/By Example.md"
  | "declaration files/Consumption.md"
  | "declaration files/Creating DTS files From JS.md"
  | "declaration files/Deep Dive.md"
  | "declaration files/Do's and Don'ts.md"
  | "declaration files/Introduction.md"
  | "declaration files/Library Structures.md"
  | "declaration files/Publishing.md"
  | "declaration files/Templates.md"
  | "declaration files/templates/global-modifying-module.d.ts.md"
  | "declaration files/templates/global-plugin.d.ts.md"
  | "declaration files/templates/global.d.ts.md"
  | "declaration files/templates/module-class.d.ts.md"
  | "declaration files/templates/module-function.d.ts.md"
  | "declaration files/templates/module-plugin.d.ts.md"
  | "declaration files/templates/module.d.ts.md"
  | "release notes/Overview.md"
  | "release notes/TypeScript 1.1.md"
  | "release notes/TypeScript 1.3.md"
  | "release notes/TypeScript 1.4.md"
  | "release notes/TypeScript 1.5.md"
  | "release notes/TypeScript 1.6.md"
  | "release notes/TypeScript 1.7.md"
  | "release notes/TypeScript 1.8.md"
  | "release notes/TypeScript 2.0.md"
  | "release notes/TypeScript 2.1.md"
  | "release notes/TypeScript 2.2.md"
  | "release notes/TypeScript 2.3.md"
  | "release notes/TypeScript 2.4.md"
  | "release notes/TypeScript 2.5.md"
  | "release notes/TypeScript 2.6.md"
  | "release notes/TypeScript 2.7.md"
  | "release notes/TypeScript 2.8.md"
  | "release notes/TypeScript 2.9.md"
  | "release notes/TypeScript 3.0.md"
  | "release notes/TypeScript 3.1.md"
  | "release notes/TypeScript 3.2.md"
  | "release notes/TypeScript 3.3.md"
  | "release notes/TypeScript 3.4.md"
  | "release notes/TypeScript 3.5.md"
  | "release notes/TypeScript 3.6.md"
  | "release notes/TypeScript 3.7.md"
  | "release notes/TypeScript 3.8.md"
  | "release notes/TypeScript 3.9.md"
  | "tutorials/ASP.NET Core.md"
  | "tutorials/Angular.md"
  | "tutorials/Babel with TypeScript.md"
  | "tutorials/DOM Manipulation.md"
  | "tutorials/Gulp.md"
  | "tutorials/Migrating from JavaScript.md"
  | "tutorials/React.md"
  | "tutorials/TypeScript Tooling in 5 minutes.md"
  | "tutorials/tsconfig.json.md";
