export type AllDocsPages =
  | "H:githubTypeScript-WebsitepackagesdocumentationcopyenNightly Builds.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyendeclaration-filesBy Example.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyendeclaration-filesConsumption.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyendeclaration-filesDeep Dive.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyendeclaration-filesDo's and Don'ts.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyendeclaration-filesIntroduction.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyendeclaration-filesLibrary Structures.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyendeclaration-filesPublishing.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyendeclaration-filesTemplates.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyendeclaration-files\templatesglobal-modifying-module.d.ts.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyendeclaration-files\templatesglobal-plugin.d.ts.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyendeclaration-files\templatesglobal.d.ts.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyendeclaration-files\templatesmodule-class.d.ts.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyendeclaration-files\templatesmodule-function.d.ts.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyendeclaration-files\templatesmodule-plugin.d.ts.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyendeclaration-files\templatesmodule.d.ts.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenget-startedTS for Functional Programmers.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenget-startedTS for JS Programmers.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenget-startedTS for OOPers.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenget-startedTS for the New Programmer.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v1Basic Types.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v1Classes.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v1Functions.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v1Generics.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v1Interfaces.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v1Literal Types.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v1Unions and Intersections.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v2Basics.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v2Classes.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v2Everyday Types.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v2Modules.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v2More on Functions.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v2Narrowing.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v2Object Types.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v2The Handbook.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v2Type Declarations.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v2Understanding Errors.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v2Type ManipulationConditional Types.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v2Type ManipulationGenerics.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v2Type ManipulationIndexed Access Types.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v2Type ManipulationKeyof Type Operator.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v2Type ManipulationMapped Types.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v2Type ManipulationTemplate Literal Types.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v2Type ManipulationTypeof Type Operator.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenhandbook-v2Type Manipulation_Creating Types from Types.md"
  | "H:githubTypeScript-WebsitepackagesdocumentationcopyenjavascriptCreating DTS files From JS.md"
  | "H:githubTypeScript-WebsitepackagesdocumentationcopyenjavascriptIntro to JS with TS.md"
  | "H:githubTypeScript-WebsitepackagesdocumentationcopyenjavascriptJSDoc Reference.md"
  | "H:githubTypeScript-WebsitepackagesdocumentationcopyenjavascriptType Checking JavaScript Files.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenproject-configCompiler Options in MSBuild.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenproject-configCompiler Options.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenproject-configConfiguring Watch.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenproject-configIntegrating with Build Tools.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenproject-configProject References.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyenproject-config\tsconfig.json.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\referenceAdvanced Types.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\referenceDeclaration Merging.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\referenceDecorators.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\referenceEnums.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\referenceIterators and Generators.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\referenceJSX.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\referenceMixins.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\referenceModule Resolution.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\referenceModules.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\referenceNamespaces and Modules.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\referenceNamespaces.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\referenceSymbols.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\referenceTriple-Slash Directives.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\referenceType Compatibility.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\referenceType Inference.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\referenceUtility Types.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\referenceVariable Declarations.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesOverview.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 1.1.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 1.3.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 1.4.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 1.5.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 1.6.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 1.7.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 1.8.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 2.0.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 2.1.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 2.2.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 2.3.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 2.4.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 2.5.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 2.6.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 2.7.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 2.8.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 2.9.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 3.0.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 3.1.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 3.2.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 3.3.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 3.4.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 3.5.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 3.6.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 3.7.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 3.8.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 3.9.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 4.0.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 4.1.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 4.2.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\release-notesTypeScript 4.3.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\tutorialsAngular.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\tutorialsASP.NET Core.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\tutorialsBabel with TypeScript.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\tutorialsDOM Manipulation.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\tutorialsGulp.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\tutorialsMigrating from JavaScript.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\tutorialsReact.md"
  | "H:githubTypeScript-Websitepackagesdocumentationcopyen\tutorialsTypeScript Tooling in 5 minutes.md";
