// @ts-check

// Ensure the versions dropdown is up to date
const nodeFetch = require('node-fetch').default
const { writeFileSync } = require('fs')
const { join } = require('path')
const { format } = require('prettier')

const go = async () => {
  const response = await nodeFetch('https://typescript.azureedge.net/indexes/releases.json')
  const json = await response.json()
  const code = `// This is auto-generated by scripts/downloadReleases.js

export const supportedReleases = ["${json.versions.join('", "')}"] as const

export type ReleaseVersions = "${json.versions.join('" | "')}"
`
  const path = join(__dirname, '..', 'src', 'releases.ts')
  writeFileSync(path, format(code, { filepath: path }), 'utf8')
  console.log('Updated the releases with the versions created by make-monaco-builds')
}

go()
