// Auto-generated by yarn workspace typescriptlang-org compile-index-examples
import React from "react"

const innerHTML = `<pre class="shiki twoslash"><div class="language-id">ts</div><div class='code-container' ><code><span style="color: #569CD6">function</span><span style="color: #D4D4D4"> <data-lsp lsp='function addPrices(items: number[]): number'>addPrices</data-lsp>(<data-lsp lsp='(parameter) items: number[]'>items</data-lsp>: number[]) {</span>
<span style="color: #D4D4D4">  </span><span style="color: #569CD6">let</span><span style="color: #D4D4D4"> <data-lsp lsp='let sum: number'>sum</data-lsp> = </span><span style="color: #B5CEA8">0</span>
<span style="color: #D4D4D4">  </span><span style="color: #569CD6">for</span><span style="color: #D4D4D4"> (</span><span style="color: #569CD6">const</span><span style="color: #D4D4D4"> <data-lsp lsp='const item: number'>item</data-lsp> </span><span style="color: #569CD6">of</span><span style="color: #D4D4D4"> <data-lsp lsp='(parameter) items: number[]'>items</data-lsp>) {</span>
<span style="color: #D4D4D4">    <data-lsp lsp='let sum: number'>sum</data-lsp> += <data-lsp lsp='const item: number'>item</data-lsp></span>
<span style="color: #D4D4D4">  }</span>
<span style="color: #D4D4D4">  </span><span style="color: #569CD6">return</span><span style="color: #D4D4D4"> <data-lsp lsp='let sum: number'>sum</data-lsp></span>
<span style="color: #D4D4D4">}</span>

<span style="color: #D4D4D4"><data-lsp lsp='function addPrices(items: number[]): number'>addPrices</data-lsp>(</span><span style="color: #B5CEA8">3</span><span style="color: #D4D4D4">, </span><span style="color: #B5CEA8">4</span><span style="color: #D4D4D4">, </span><span style="color: #B5CEA8">6</span><span style="color: #D4D4D4">)</span>
<span class="error"><span>Expected 1 arguments, but got 3.</span><span class="code">2554</span></span><span class="error-behind">Expected 1 arguments, but got 3.</span></code></div></pre>`

export const ShowErrorsExample = () => <div dangerouslySetInnerHTML={{ __html: innerHTML }} />
