export const handbookCopy = {
  handb_prev: "上一篇",
  handb_next: "下一篇",
  handb_on_this_page: "在本页",
  handb_like_dislike_title: "本页面对你有帮助吗？",
  handb_like_desc: "是",
  handb_dislike_desc: "否",
  handb_thanks: "感谢反馈",
  handb_deprecated_title: "本页面已废弃",
  handb_deprecated_subtitle: "本手册已被取代，",
  handb_deprecated_subtitle_link: "前往新页面",
  handb_deprecated_subtitle_action: "前往新页面",
  handb_experimental_title: "本页面包含实验性文档",
  handb_experimental_subtitle: "内容涉及正在进行中的主题。",
}
