// This is auto-generated by scripts/downloadReleases.js
define(["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.supportedReleases = void 0;
    exports.supportedReleases = [
        "3.9.2",
        "3.8.3",
        "3.8.2",
        "3.7.5",
        "3.6.3",
        "3.5.1",
        "3.3.3",
        "3.1.6",
        "3.0.1",
        "2.8.1",
        "2.7.2",
        "2.4.1",
    ];
});
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicmVsZWFzZXMuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyIuLi8uLi8uLi8uLi9zYW5kYm94L3NyYy9yZWxlYXNlcy50cyJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFBQSx3REFBd0Q7Ozs7O0lBRTNDLFFBQUEsaUJBQWlCLEdBQUc7UUFDL0IsT0FBTztRQUNQLE9BQU87UUFDUCxPQUFPO1FBQ1AsT0FBTztRQUNQLE9BQU87UUFDUCxPQUFPO1FBQ1AsT0FBTztRQUNQLE9BQU87UUFDUCxPQUFPO1FBQ1AsT0FBTztRQUNQLE9BQU87UUFDUCxPQUFPO0tBQ0MsQ0FBQyIsInNvdXJjZXNDb250ZW50IjpbIi8vIFRoaXMgaXMgYXV0by1nZW5lcmF0ZWQgYnkgc2NyaXB0cy9kb3dubG9hZFJlbGVhc2VzLmpzXG5cbmV4cG9ydCBjb25zdCBzdXBwb3J0ZWRSZWxlYXNlcyA9IFtcbiAgXCIzLjkuMlwiLFxuICBcIjMuOC4zXCIsXG4gIFwiMy44LjJcIixcbiAgXCIzLjcuNVwiLFxuICBcIjMuNi4zXCIsXG4gIFwiMy41LjFcIixcbiAgXCIzLjMuM1wiLFxuICBcIjMuMS42XCIsXG4gIFwiMy4wLjFcIixcbiAgXCIyLjguMVwiLFxuICBcIjIuNy4yXCIsXG4gIFwiMi40LjFcIixcbl0gYXMgY29uc3Q7XG5cbmV4cG9ydCB0eXBlIFJlbGVhc2VWZXJzaW9ucyA9XG4gIHwgXCIzLjkuMlwiXG4gIHwgXCIzLjguM1wiXG4gIHwgXCIzLjguMlwiXG4gIHwgXCIzLjcuNVwiXG4gIHwgXCIzLjYuM1wiXG4gIHwgXCIzLjUuMVwiXG4gIHwgXCIzLjMuM1wiXG4gIHwgXCIzLjEuNlwiXG4gIHwgXCIzLjAuMVwiXG4gIHwgXCIyLjguMVwiXG4gIHwgXCIyLjcuMlwiXG4gIHwgXCIyLjQuMVwiO1xuIl19