name: Keep alive
on:
  schedule:
    - cron: "0 0 * * *"
    
jobs:
  keepalive:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - run: |
          if [[ $(git log --format="%H" --since "50 days" | head -c1 | wc -c) == 0 ]]; then
            git config user.email "typescriptbot@microsoft.com"
            git config user.name "TypeScript Bot"
            git commit --allow-empty -m "Automated commit to keep GitHub Actions active"
            git push
          fi
