name: Keep alive
on:
  schedule:
    - cron: "0 0 * * *"
    
jobs:
  keepalive:
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/TypeScript-Website'

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - run: |
          if [[ $(git log --format="%H" --since "50 days" | head -c1 | wc -c) == 0 ]]; then
            git config user.email "typescriptbot@microsoft.com"
            git config user.name "TypeScript Bot"
            git commit --allow-empty -m "Automated commit to keep GitHub Actions active"
            git push
          fi
