name: Keep alive
on:
  schedule:
    - cron: "0 0 * * *"
    
jobs:
  keepalive:
    runs-on: ubuntu-latest
    if: github.repository == 'microsoft/TypeScript-Website'

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: |
          if [[ $(git log --format="%H" --since "50 days" | head -c1 | wc -c) == 0 ]]; then
            git config user.email "290192711+typescript-automation[bot]@users.noreply.github.com"
            git config user.name "typescript-automation[bot]"
            git commit --allow-empty -m "Automated commit to keep GitHub Actions active"
            git push
          fi
